SET search_path TO "defaults";

-- Popula a tabela de default_products
INSERT INTO "tb_default_product" ("name", "cd_unit_type", "cd_default_category") VALUES 
('Pão', 1, 10),
('Arroz', 2, 12),
('Feijão', 2, 12),
('Creme dental', 4, 9),
('Escova de dentes', 4, 9),
('Enxaguante bucal', 4, 9),
('Desodorante', 4, 9),
('Cotonete', 4, 9),
('Creme de pentear', 4, 9),
('Esponja de banho', 4, 9),
('Sabonete', 4, 9),
('Shampoo', 4, 9),
('Condicionador', 4, 9),
('Papel higiênico', 3, 9),
('Mostarda', 4, 4),
('Ketchup', 4, 4),
('Molho de pimenta', 4, 4),
('Sal', 1, 4),
('Óleo', 5, 4),
('Salsicha', 3, 3),
('Linguiça', 2, 3),
('Peixe', 2, 3),
('Atum', 2, 3),
('Sardinha', 2, 3),
('Carne', 2, 3),
('Frango', 2, 3),
('Margarina', 4, 1),
('Manteiga', 4, 1),
('Iogurte', 4, 1),
('Geléia', 4, 1),
('Leite', 5, 1),
('Queijo', 1, 1),
('Presunto', 1, 1),
('Leite condensado', 4, 1),
('Creme de leite', 4, 1),
('Gelatina', 4, 1),
('Ricota', 4, 1),
('Requeijão', 4, 1),
('Cereal', 4, 6),
('Granola', 2, 6),
('Aveia', 2, 6),
('Biscoitos', 4, 6),
('Bolacha', 4, 6),
('Chocolate', 4, 6),
('Balas', 4, 6),
('Chiclete', 4, 6),
('Pipoca', 4, 6),
('Amendoim', 4, 6),
('Castanhas', 4, 6),
('Nozes', 4, 6),
('Pistache', 4, 6),
('Ovos', 7, 6),
('Farinha de trigo', 2, 6),
('Macarrão', 3, 6),
('Geleia real', 4, 6),
('Mel', 4, 6),
('Creme de avelã', 4, 6),
('Pasta de amendoim', 4, 6),
('Marshmallows', 4, 6),
('Açúcar mascavo', 4, 6),
('Adoçante', 4, 6),
('Melado', 4, 6),
('Chantilly', 4, 6),
('Açucar', 4, 6),
('Cerveja', 4, 7),
('Vinho', 4, 7),
('Espumante', 4, 7),
('Vodka', 4, 7),
('Whisky', 4, 7),
('Tequila', 4, 7),
('Rum', 4, 7),
('Martini', 4, 7),
('Campari', 4, 7),
('Licor', 4, 7),
('Suco', 5, 7),
('Refrigerante', 5, 7),
('Suco de pozinho', 4, 7),
('Água', 4, 7),
('Água com gáz', 4, 7),
('Chá', 4, 7),
('Achocolatado', 4, 7),
('Café', 4, 7),
('Vinagre', 5, 7),
('Azeitonas', 4, 11),
('Molho de tomate', 4, 11),
('Picles', 4, 11),
('Frutas em calda', 4, 11),
('Patê', 4, 11),
('Manga', 2, 5),
('Banana', 2, 5),
('Maçã', 2, 5),
('Laranja', 2, 5),
('Cebola', 2, 5),
('Alho', 1, 5),
('Batata', 2, 5),
('Uva', 2, 5),
('Tomate', 2, 5),
('Pano de limpeza', 4, 8),
('Sabão em pó', 2, 8),
('Esponja de cozinha', 4, 8),
('Detergente', 4, 8),
('Amaciante', 4, 8),
('Desinfectante', 4, 8),
('Alvejante', 4, 8),
('Limpador multiúso', 4, 8);
