from app.DataBase.models.defualt_product_models import NewDefaultProduct
from app.Enums.enums import LangEnum
from app.Services.default_products_service import DefaultProductsService


class Populate:
    def __init__(self) -> None:
        default_products: list[NewDefaultProduct] = [
            NewDefaultProduct(
                name="Manga",
                unit_type_name="Kilos",
                default_category_name="Hortifrúti",
            ),
            NewDefaultProduct(
                name="Banana",
                unit_type_name="Kilos",
                default_category_name="Hortifrúti",
            ),
            NewDefaultProduct(
                name="Arroz",
                unit_type_name="Kilos",
                default_category_name="Bazar",
            ),
            NewDefaultProduct(
                name="Feijão",
                unit_type_name="Kilos",
                default_category_name="Bazar",
            ),
            NewDefaultProduct(
                name="Carne",
                unit_type_name="Gramas",
                default_category_name="Carnes",
            ),
            NewDefaultProduct(
                name="Frango",
                unit_type_name="Kilos",
                default_category_name="Carnes",
            ),
            NewDefaultProduct(
                name="Café",
                unit_type_name="Gramas",
                default_category_name="Bebidas",
            ),
            NewDefaultProduct(
                name="Açúcar",
                unit_type_name="Kilos",
                default_category_name="Condimentos",
            ),
            NewDefaultProduct(
                name="Sal",
                unit_type_name="Gramas",
                default_category_name="Condimentos",
            ),
            NewDefaultProduct(
                name="Óleo",
                unit_type_name="Litros",
                default_category_name="Condimentos",
            ),
            NewDefaultProduct(
                name="Leite",
                unit_type_name="Litros",
                default_category_name="Laticínios",
            ),
            NewDefaultProduct(
                name="Queijo",
                unit_type_name="Gramas",
                default_category_name="Laticínios",
            ),
            NewDefaultProduct(
                name="Presunto",
                unit_type_name="Gramas",
                default_category_name="Laticínios",
            ),
            NewDefaultProduct(
                name="Pão",
                unit_type_name="Gramas",
                default_category_name="Padaria",
            ),
            NewDefaultProduct(
                name="Macarrão",
                unit_type_name="Pacote",
                default_category_name="Bazar",
            ),
            NewDefaultProduct(
                name="Molho de tomate",
                unit_type_name="Unidade",
                default_category_name="Enlatados",
            ),
            NewDefaultProduct(
                name="Farinha de trigo",
                unit_type_name="Kilos",
                default_category_name="Bazar",
            ),
            NewDefaultProduct(
                name="Ovos",
                unit_type_name="Caixa",
                default_category_name="Bazar",
            ),
            NewDefaultProduct(
                name="Maçã",
                unit_type_name="Kilos",
                default_category_name="Hortifrúti",
            ),
            NewDefaultProduct(
                name="Laranja",
                unit_type_name="Kilos",
                default_category_name="Hortifrúti",
            ),
            NewDefaultProduct(
                name="Cebola",
                unit_type_name="Kilos",
                default_category_name="Hortifrúti",
            ),
            NewDefaultProduct(
                name="Alho",
                unit_type_name="Gramas",
                default_category_name="Hortifrúti",
            ),
            NewDefaultProduct(
                name="Batata",
                unit_type_name="Kilos",
                default_category_name="Hortifrúti",
            ),
            NewDefaultProduct(
                name="Tomate",
                unit_type_name="Kilos",
                default_category_name="Hortifrúti",
            ),
            NewDefaultProduct(
                name="Suco",
                unit_type_name="Litros",
                default_category_name="Bebidas",
            ),
            NewDefaultProduct(
                name="Refrigerante",
                unit_type_name="Litros",
                default_category_name="Bebidas",
            ),
            NewDefaultProduct(
                name="Suco de pozinho",
                unit_type_name="Unidade",
                default_category_name="Bebidas",
            ),
            NewDefaultProduct(
                name="Água",
                unit_type_name="Unidade",
                default_category_name="Bebidas",
            ),
            NewDefaultProduct(
                name="Água com gáz",
                unit_type_name="Unidade",
                default_category_name="Bebidas",
            ),
            NewDefaultProduct(
                name="Sabonete",
                unit_type_name="Unidade",
                default_category_name="Higiene Pessoal",
            ),
            NewDefaultProduct(
                name="Shampoo",
                unit_type_name="Unidade",
                default_category_name="Higiene Pessoal",
            ),
            NewDefaultProduct(
                name="Condicionador",
                unit_type_name="Unidade",
                default_category_name="Higiene Pessoal",
            ),
            NewDefaultProduct(
                name="Papel higiênico",
                unit_type_name="Pacote",
                default_category_name="Higiene Pessoal",
            ),
            NewDefaultProduct(
                name="Detergente",
                unit_type_name="Unidade",
                default_category_name="Limpeza",
            ),
            NewDefaultProduct(
                name="Amaciante",
                unit_type_name="Unidade",
                default_category_name="Limpeza",
            ),
            NewDefaultProduct(
                name="Desinfectante",
                unit_type_name="Unidade",
                default_category_name="Limpeza",
            ),
            NewDefaultProduct(
                name="Alvejante",
                unit_type_name="Unidade",
                default_category_name="Limpeza",
            ),
            NewDefaultProduct(
                name="Limpador multiúso",
                unit_type_name="Unidade",
                default_category_name="Limpeza",
            ),
            NewDefaultProduct(
                name="Creme dental",
                unit_type_name="Unidade",
                default_category_name="Higiene Pessoal",
            ),
            NewDefaultProduct(
                name="Escova de dentes",
                unit_type_name="Unidade",
                default_category_name="Higiene Pessoal",
            ),
            NewDefaultProduct(
                name="Enxaguante bucal",
                unit_type_name="Unidade",
                default_category_name="Higiene Pessoal",
            ),
            NewDefaultProduct(
                name="Desodorante",
                unit_type_name="Unidade",
                default_category_name="Higiene Pessoal",
            ),
            NewDefaultProduct(
                name="Sabão em pó",
                unit_type_name="Kilos",
                default_category_name="Limpeza",
            ),
            NewDefaultProduct(
                name="Esponja de cozinha",
                unit_type_name="Unidade",
                default_category_name="Limpeza",
            ),
            NewDefaultProduct(
                name="Leite condensado",
                unit_type_name="Unidade",
                default_category_name="Laticínios",
            ),
            NewDefaultProduct(
                name="Creme de leite",
                unit_type_name="Unidade",
                default_category_name="Laticínios",
            ),
            NewDefaultProduct(
                name="Gelatina",
                unit_type_name="Unidade",
                default_category_name="Laticínios",
            ),
            NewDefaultProduct(
                name="Chá",
                unit_type_name="Unidade",
                default_category_name="Bebidas",
            ),
            NewDefaultProduct(
                name="Vinagre",
                unit_type_name="Litros",
                default_category_name="Bebidas",
            ),
            NewDefaultProduct(
                name="Mostarda",
                unit_type_name="Unidade",
                default_category_name="Condimentos",
            ),
            NewDefaultProduct(
                name="Ketchup",
                unit_type_name="Unidade",
                default_category_name="Condimentos",
            ),
            NewDefaultProduct(
                name="Molho de pimenta",
                unit_type_name="Unidade",
                default_category_name="Condimentos",
            ),
            NewDefaultProduct(
                name="Salsicha",
                unit_type_name="Pacote",
                default_category_name="Carnes",
            ),
            NewDefaultProduct(
                name="Linguiça",
                unit_type_name="Kilos",
                default_category_name="Carnes",
            ),
            NewDefaultProduct(
                name="Peixe",
                unit_type_name="Kilos",
                default_category_name="Carnes",
            ),
            NewDefaultProduct(
                name="Atum",
                unit_type_name="Kilos",
                default_category_name="Carnes",
            ),
            NewDefaultProduct(
                name="Sardinha",
                unit_type_name="Kilos",
                default_category_name="Carnes",
            ),
            NewDefaultProduct(
                name="Margarina",
                unit_type_name="Unidade",
                default_category_name="Laticínios",
            ),
            NewDefaultProduct(
                name="Manteiga",
                unit_type_name="Unidade",
                default_category_name="Laticínios",
            ),
            NewDefaultProduct(
                name="Iogurte",
                unit_type_name="Unidade",
                default_category_name="Laticínios",
            ),
            NewDefaultProduct(
                name="Geléia",
                unit_type_name="Unidade",
                default_category_name="Laticínios",
            ),
            NewDefaultProduct(
                name="Cereal",
                unit_type_name="Unidade",
                default_category_name="Bazar",
            ),
            NewDefaultProduct(
                name="Granola",
                unit_type_name="Kilos",
                default_category_name="Bazar",
            ),
            NewDefaultProduct(
                name="Aveia",
                unit_type_name="Kilos",
                default_category_name="Bazar",
            ),
            NewDefaultProduct(
                name="Biscoitos",
                unit_type_name="Unidade",
                default_category_name="Bazar",
            ),
            NewDefaultProduct(
                name="Bolacha",
                unit_type_name="Unidade",
                default_category_name="Bazar",
            ),
            NewDefaultProduct(
                name="Chocolate",
                unit_type_name="Unidade",
                default_category_name="Bazar",
            ),
            NewDefaultProduct(
                name="Achocolatado",
                unit_type_name="Unidade",
                default_category_name="Bebidas",
            ),
            NewDefaultProduct(
                name="Balas",
                unit_type_name="Unidade",
                default_category_name="Bazar",
            ),
            NewDefaultProduct(
                name="Chiclete",
                unit_type_name="Unidade",
                default_category_name="Bazar",
            ),
            NewDefaultProduct(
                name="Pipoca",
                unit_type_name="Unidade",
                default_category_name="Bazar",
            ),
            NewDefaultProduct(
                name="Amendoim",
                unit_type_name="Unidade",
                default_category_name="Bazar",
            ),
            NewDefaultProduct(
                name="Castanhas",
                unit_type_name="Unidade",
                default_category_name="Bazar",
            ),
            NewDefaultProduct(
                name="Nozes",
                unit_type_name="Unidade",
                default_category_name="Bazar",
            ),
            NewDefaultProduct(
                name="Pistache",
                unit_type_name="Unidade",
                default_category_name="Bazar",
            ),
            NewDefaultProduct(
                name="Cerveja",
                unit_type_name="Unidade",
                default_category_name="Bebidas",
            ),
            NewDefaultProduct(
                name="Vinho",
                unit_type_name="Unidade",
                default_category_name="Bebidas",
            ),
            NewDefaultProduct(
                name="Espumante",
                unit_type_name="Unidade",
                default_category_name="Bebidas",
            ),
            NewDefaultProduct(
                name="Vodka",
                unit_type_name="Unidade",
                default_category_name="Bebidas",
            ),
            NewDefaultProduct(
                name="Whisky",
                unit_type_name="Unidade",
                default_category_name="Bebidas",
            ),
            NewDefaultProduct(
                name="Tequila",
                unit_type_name="Unidade",
                default_category_name="Bebidas",
            ),
            NewDefaultProduct(
                name="Rum",
                unit_type_name="Unidade",
                default_category_name="Bebidas",
            ),
            NewDefaultProduct(
                name="Martini",
                unit_type_name="Unidade",
                default_category_name="Bebidas",
            ),
            NewDefaultProduct(
                name="Campari",
                unit_type_name="Unidade",
                default_category_name="Bebidas",
            ),
            NewDefaultProduct(
                name="Licor",
                unit_type_name="Unidade",
                default_category_name="Bebidas",
            ),
            NewDefaultProduct(
                name="Azeitonas",
                unit_type_name="Unidade",
                default_category_name="Enlatados",
            ),
            NewDefaultProduct(
                name="Picles",
                unit_type_name="Unidade",
                default_category_name="Enlatados",
            ),
            NewDefaultProduct(
                name="Frutas em calda",
                unit_type_name="Unidade",
                default_category_name="Enlatados",
            ),
            NewDefaultProduct(
                name="Geleia real",
                unit_type_name="Unidade",
                default_category_name="Bazar",
            ),
            NewDefaultProduct(
                name="Mel",
                unit_type_name="Unidade",
                default_category_name="Bazar",
            ),
            NewDefaultProduct(
                name="Creme de avelã",
                unit_type_name="Unidade",
                default_category_name="Bazar",
            ),
            NewDefaultProduct(
                name="Pasta de amendoim",
                unit_type_name="Unidade",
                default_category_name="Bazar",
            ),
            NewDefaultProduct(
                name="Marshmallows",
                unit_type_name="Unidade",
                default_category_name="Bazar",
            ),
            NewDefaultProduct(
                name="Açúcar mascavo",
                unit_type_name="Unidade",
                default_category_name="Bazar",
            ),
            NewDefaultProduct(
                name="Adoçante",
                unit_type_name="Unidade",
                default_category_name="Bazar",
            ),
            NewDefaultProduct(
                name="Melado",
                unit_type_name="Unidade",
                default_category_name="Bazar",
            ),
            NewDefaultProduct(
                name="Chantilly",
                unit_type_name="Unidade",
                default_category_name="Bazar",
            ),
            NewDefaultProduct(
                name="Patê",
                unit_type_name="Unidade",
                default_category_name="Enlatados",
            ),
            NewDefaultProduct(
                name="Ricota",
                unit_type_name="Unidade",
                default_category_name="Laticínios",
            ),
            NewDefaultProduct(
                name="Requeijão",
                unit_type_name="Unidade",
                default_category_name="Laticínios",
            ),
        ]

        for product in default_products:
            DefaultProductsService().create_new_default_product(product, LangEnum.PT_BR)


if __name__ == "__main__":
    Populate()
