services:
  postgres:
    image: postgres:16
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init_data/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db_network
    shm_size: 128mb

volumes:
  db_data:

networks:
  db_network:
    driver: bridge
