services:
  postgres:
    image: postgres:16
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init_data:/docker-entrypoint-initdb.d
    networks:
      - db_network
    shm_size: 128mb
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - db_network
    shm_size: 128mb
    
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev"]
    ports:
      - "8080:8080"

volumes:
  db_data:

networks:
  db_network:
    driver: bridge
